#ifndef CONSTANTS_H
#define CONSTANTS_H

#define FONT_SIZE_BUT 16
#define FONT_SIZE_TITLE 40
#define NUM_MENU_BUTTONS 4
#define NUM_SETTINGS_BUTTONS 2
#define SCREEN_HEIGHT 800
#define SCREEN_WIDTH 800
#define TITLE "RTS Minesweeper"
#define BACK_BUTTON_TITLE "BACK"
#define APPLY_BUTTON_TITLE "APPLY"
#define START_BUTTON_TITLE "START"
#define STATS_BUTTON_TITLE "STATISTICS"
#define SETTINGS_BUTTON_TITLE "SETTINGS"
#define QUIT_BUTTON_TITLE "QUIT"

#endif