#ifndef CONSTANTS_H
#define CONSTANTS_H

#define FONT_SIZE_BUT 16
#define FONT_SIZE_TITLE 40
#define INITIAL_SCREEN_HEIGHT 800
#define INITIAL_SCREEN_WIDTH 800
#define GAME_TITLE "RTS Minesweeper"

#endif