#ifndef CONSTANTS_H
#define CONSTANTS_H

#define FONT_SIZE_BUT 16
#define FONT_SIZE_TITLE 40
#define NUM_MENU_BUTTONS 4
#define NUM_SETTINGS_BUTTONS 2
#define INITIAL_SCREEN_HEIGHT 800
#define INITIAL_SCREEN_WIDTH 800
#define GAME_TITLE "RTS Minesweeper"
#define BACK_BUTTON_TITLE "BACK"
#define APPLY_BUTTON_TITLE "APPLY"
#define START_BUTTON_TITLE "START"
#define STATS_BUTTON_TITLE "STATISTICS"
#define SETTINGS_BUTTON_TITLE "SETTINGS"
#define QUIT_BUTTON_TITLE "QUIT"

#define START_BUTTON_INTEGER 0
#define SETTINGS_BUTTON_INTEGER 1
#define STATS_BUTTON_INTEGER 2
#define QUIT_BUTTON_INTEGER 3
#define BACK_BUTTON_INTEGER 0
#define APPLY_BUTTON_INTEGER 1
#define START_GAME_BUTTON_INTEGER 1

#define NO_CLICKS 0
#endif